services:
  mysql:
    image: mysql:8.4
    container_name: crimsonCitadel_JeongWonWoo
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: CrimsonCitadel
    ports:
      - "3306:3306"